### ISSUE TITLE
Display backend/frontend/infra version number on website

### ISSUE THREAD

**Issue by n8kim1** [battlecode/battlehack20#60]
Not sure how this would work tbh, but would be incredibly helpful for debugging and deployment

**Comment by n8kim1** [comment]
resolved by virtue of nonurgency

**Comment by n8kim1** [comment]
idea: scrimmage server version number could be reported in db? along w the rest of the scrimmage output

**Comment by n8kim1** [comment]
This may be possible through sed in the dockerfile! (Also if dockerfiles have a built-in way to attach version number / build time, that would be even better.)

Unfortunately it may prevent using cached builds (bc every time you try to build, a little string gets changed).

**Comment by n8kim1** [comment]
Also we'd have to be careful that this works both locally and deployed; the build processes use slightly different files.

**Comment by j-mao** [comment]
Would it be possible to set the version last? eg. have it as an env var and then set the env in the last dockerfile rule. This would get past the docker cache, does this work with the current backend/frontend setup?
