### ISSUE TITLE
sense() is only sensing in one quadrant of 5x5 square

### ISSUE THREAD

**Issue by StoneT2000** [battlecode/battlehack20#74]
Original code at https://github.com/battlecode/battlehack20/blob/master/engine/battlehack20/engine/game/game.py#L375 has
```
for i in range(self.sensor_radius, self.sensor_radius + 1):
    for j in range(self.sensor_radius, self.sensor_radius + 1):
```

I believe it should be

```
for i in range( -self.sensor_radius, self.sensor_radius + 1):
    for j in range( -self.sensor_radius, self.sensor_radius + 1):
    ....
```
The original is going from `self.sensor_radius` to `self.sensor_radius + 1`, of which `range` just gives `2`
`range(-self.sensor_radius to self.sensor_radius + 1)` will produce the correct deltas from -2 to 2

**Comment by arvid220u** [comment]
lol thanks
