### ISSUE TITLE
Duplication of Bots with Same IDs

### ISSUE THREAD

**Issue by fenwicktreeguy** [battlecode/battlehack20#78]
I was attempting a crosshatched pawn strategy starting game when the back row of white pawns seemingly duplicated itself forward in an attempt to move forward.

PUT_COL_WHITE = 0
PUT_COL_BLACK = 0
PUT_ROW_BLACK = 15
PUT_ROW_WHITE = 0
FIRST_PHASE = 7
run = True

occupiedBlack = [False for x in range(0,16)]
oocupiedWhite = [False for x in range(0,16)]

runWhite = True
runBlack = False
opponent = Team.BLACK

DEBUG = 1
def dlog(str):
    global DEBUG
    if DEBUG > 0:
        log(str)

def start_game():
        global PUT_ROW_BLACK
        global PUT_ROW_WHITE
        global PUT_COL_BLACK
        global PUT_COL_WHITE

        global opponent
        opponent = Team.BLACK if get_team() == Team.WHITE else Team.WHITE

        global occupiedBlack
        dlog("OPPONENT: " + str(opponent) )
        if(opponent == Team.WHITE):
            dlog("BLACK STATUS: " + str(PUT_COL_BLACK))
            if(PUT_COL_BLACK < 15):
                    dlog("PAWN PLACED AT: " + str(PUT_ROW_BLACK) + " " + str(PUT_COL_BLACK))
                    spawn(PUT_ROW_BLACK, PUT_COL_BLACK)
                    #occupiedBlack[PUT_COL_BLACK] = True
                    PUT_COL_BLACK += 2
            elif(PUT_COL_BLACK >= 15):
                dlog("moving...")
                move_forward()
        elif(opponent == Team.BLACK):
                if(PUT_COL_WHITE < 15):
                        #dlog("PAWN PLACED AT: " + str(PUT_ROW_WHITE) + " " + str(PUT_COL_WHITE))
                        spawn(PUT_ROW_WHITE, PUT_COL_WHITE)
                        #occupiedWhite[PUT_COL_WHITE] = True
                        PUT_COL_WHITE += 2
                elif(PUT_COL_WHITE == 15):
                    dlog("moving...")
                    move_forward()

def turn():
    start_game()

![Screen Shot 2020-04-17 at 10 14 13 AM](https://user-images.githubusercontent.com/26752309/79578807-b9dcec80-8094-11ea-9915-931625b35a6f.png)

**Comment by arvid220u** [comment]
does this still happen on 1.0.2?

**Comment by fenwicktreeguy** [comment]
It seems not.

**Comment by arvid220u** [comment]
great!
