### ISSUE TITLE
The reason for the line confused = "" being needed to make the example code work is the result of a bug in the engine

### ISSUE THREAD

**Issue by BenjaminKovacs** [battlecode/battlehack20#92]
When instrument.py adds an instruction, it increases the number of bytes forward which jump commands jump. When this number is increased from below 256 to above 256, the operator EXTENDED_ARGS is added before the jump operator. This results in other jump operators being changed to account for the additional operator. The problem is that any jump that goes to the jump operator which just had EXTENDED_ARGS added before it is also changed such that it skips over the EXTENDED_ARGS. 
![image](https://user-images.githubusercontent.com/8866478/79624060-46b39480-80ed-11ea-869c-a91823fd9bdf.png)
In this example, the jump command on 396 has been incorrectly changed to skip EXTENDED_ARG on 418, resulting in Windows fatal exception: access violation
(the code on the left does not work, the code on the right does)
[bot.txt](https://github.com/battlecode/battlehack20/files/4495787/bot.txt)
Here is the python code itself. The error can be seen by uncommenting line 75

**Comment by arvid220u** [comment]
This is great find!! It took me a lot of time to find this :)) — but this was in fact fixed in #76. The solution is exactly as you say!

Also, make sure you run `pip install --user --upgrade battlehack20` frequently so that you get new updates like this one.
